# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7d39ec5bc022fac9dec80a009967072bc9655b9e76c26ccb8c5cb26f502e4d5938477578c43555877fc79e64a82b0b6d9ee195f20b9870a0947aa3d235929e2

test:
  secret_key_base: 831de59ecb6f5e466b7ce85314cb84e1403833086d9a2817a5d5b47dc68ba941daf694abd28f8d902a64f7c0a55c09a7dba4d61d46572657193cecf24d11e5c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
